## 学习Numpy

In [1]:
import numpy

In [2]:
numpy.version.full_version

'1.12.1'

In [3]:
import numpy as np

In [4]:
a = np.array([0,1,2,3,4,5])

In [5]:
a

array([0, 1, 2, 3, 4, 5])

In [6]:
a.ndim

1

In [7]:
a.shape

(6,)

In [8]:
b = a.reshape((3,2))

In [9]:
b.ndim

2

In [10]:
b.shape

(3, 2)

**当b更改时，a也更改**

In [11]:
b[1][0] = 77

In [12]:
b

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [13]:
a

array([ 0,  1, 77,  3,  4,  5])

需要一个副本时，请用**copy**

In [17]:
c = a.reshape((3,2)).copy()
c

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [18]:
c[0][0] = 99

In [19]:
a

array([ 0,  1, 77,  3,  4,  5])

In [20]:
a * 2

array([  0,   2, 154,   6,   8,  10])

In [21]:
a ** 2

array([   0,    1, 5929,    9,   16,   25])

In [22]:
a[np.array([2,3,4])]

array([77,  3,  4])

In [23]:
a > 4

array([False, False,  True, False, False,  True], dtype=bool)

In [24]:
a[a>4]

array([77,  5])

In [25]:
a[a>4]=4

In [26]:
a

array([0, 1, 4, 3, 4, 4])

专门的修剪函数 **clip**

In [27]:
a.clip(1,2)

array([1, 1, 2, 2, 2, 2])

### 处理不存在的值

In [29]:
c = np.array([1,2, np.NAN,3,4])

In [30]:
c

array([  1.,   2.,  nan,   3.,   4.])

In [31]:
np.isnan(c)

array([False, False,  True, False, False], dtype=bool)

In [32]:
c[~np.isnan(c)]

array([ 1.,  2.,  3.,  4.])

In [33]:
np.mean(c[~np.isnan(c)])

2.5

## 运行时行为比较

**timeit**

In [34]:
import timeit

In [39]:
normal_py_sec = timeit.timeit('sum(x*x for x in range(1000))', number=10000)

naive_np_sec = timeit.timeit('sum(na*na)', setup='import numpy as np; na=np.arange(1000)', number=10000)

good_np_sec = timeit.timeit('na.dot(na)', setup="import numpy as np; na=np.arange(1000)", number=10000)

print("Normal Python:\t%f sec" % normal_py_sec)

print("Naive NumPy:\t%fsec" % naive_np_sec)

print("Good Numpy:\t%f sec" % good_np_sec)

Normal Python	:	0.928119 sec
Naive NumPy	:	0.804570sec
Good Numpy	:	0.015855 sec


在要实现的算法中，应时常考虑如何将数组元循环处理从Python中移到高度优化的Numpy或SciPy扩展函数中。
速度有代价。NumPy数组中只有一个数据类型

In [40]:
a = np.array([1,2,3])
a.dtype

dtype('int64')

In [41]:
np.array([1, "stringy"])

array(['1', 'stringy'], 
      dtype='<U21')

In [42]:
np.array([1, "string", set([1,2,3])])

array([1, 'string', {1, 2, 3}], dtype=object)